name: alethic-ism-processor-anthropic
channels:
  - file:///app/conda/env/local_channel
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - python-dotenv
  - psycopg2
  - pyyaml
  - pydantic
  - anthropic
  - restrictedpython
  - nats-py
  - redis-py
  - tenacity
  - mako
  - alethic-ism-core
  - alethic-ism-db
